[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 10

[font.normal]
family = "Hack Nerd Font"

[mouse]
hide_when_typing = true

[window]
opacity = 0.8
